### ISSUE TITLE
Unexpected token "?" at command/lib/command.js

### ISSUE THREAD

**Issue by techy804** [hackermondev/replit-exporter#3]
Hi, I'm trying to download my Replits and came across this program
I run Windows 11, so I figured I'd use Ubuntu WSL to do this NPM script.

I got the cookie C+Ped and an output ready
![image](https://github.com/user-attachments/assets/c4aa3a09-b4e5-4d71-a1ff-c4ab344a6157)

**Comment by hackermondev** [comment]
@techy804 try updating your node version. 

also it doesn't support auth cookies from files yet, you have to use the raw cookie value for the arg

**Comment by techy804** [comment]
I installed node via APT this morning, for some reason it installed v12, I used nvm to update it to the current LTS version, v20.
