### ISSUE TITLE
Logging suggestion

### ISSUE THREAD

**Issue by domluther** [hackermondev/replit-exporter#5]
Thank you so much for putting this together - so useful after these recent changes by replit. 

One thing that might be useful is to be more clear about logging when it successfully manages to download a repl. Amid all the 409s and messages about rate limiting, I had no idea that this was actually working until I looked at my repls folder.

When I looked back, there was the 
2024-08-28T07:46:35.048Z Downloading 15 repls (30 finished).
but that was lost in the sea of 

2024-08-28T07:46:36.470Z Retrying request to https://replit.com/@....zip(1), recieved status code 409

and

2024-08-28T07:46:38.446Z https://replit.com/...zip ratelimited, automatically retrying in 15 seconds

Also - in a different comment you say the rate limiting is 45 in 30 minutes. If that's the case, would it be better practice to change the automatic retry to something longer if you know it's going to do that 100 times you're sending them lots of requests that you know will fail.

**Comment by hackermondev** [comment]
Thanks for the suggestion, I've implemented logging (8b7ca46e394b43b80d8967cbbac6435992c737d2) and a higher retry seconds (https://github.com/hackermondev/replit-exporter/commit/e9b3830ba85ff8ca947b1d480b6336a8b09a192c), (forgot about ratelimit until after I committed the first commit xd). 

I've set the retry seconds to about ~2 minute instead. My comment about the rate limit was something I heard from another community member and it's just speculation. In my experience, sometimes its even much shorter so I didn't want to use a high number.
